# configs/sae_config.yaml

hidden_dim: 16384
activation: relu

sparsity_penalty: 0.0001
sparsity_target: 0.03

lr: 0.001
batch_size: 16
epochs: 10

layer_index: 12
train_size: 10000  # for IVFFLAT training if needed
